
// This file has been generated by the GUI designer. Do not modify.
namespace BoottaWidgets
{
	public partial class BTable
	{
		private global::Gtk.Table tblBTableWidgetContainer;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget BoottaWidgets.BTable
			global::Stetic.BinContainer.Attach (this);
			this.Name = "BoottaWidgets.BTable";
			// Container child BoottaWidgets.BTable.Gtk.Container+ContainerChild
			this.tblBTableWidgetContainer = new global::Gtk.Table (((uint)(3)), ((uint)(3)), false);
			this.tblBTableWidgetContainer.Name = "tblBTableWidgetContainer";
			this.Add (this.tblBTableWidgetContainer);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
