
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox4;
	
	private global::Gtk.HBox hbox3;
	
	private global::Gtk.Image imgLogo;
	
	private global::Gtk.HBox hbox4;
	
	private global::Gtk.VBox vbox2;
	
	private global::Gtk.Fixed fixed10;
	
	private global::Gtk.HBox hbox24;
	
	private global::Gtk.HBox hbox25;
	
	private global::Gtk.HBox hbox26;
	
	private global::Gtk.VBox vbox5;
	
	private global::Gtk.Notebook notebook2;
	
	private global::Gtk.Label pgShritt1;
	
	private global::Gtk.VBox vbox6;
	
	private global::Gtk.Label label5;
	
	private global::Gtk.VBox vbox7;
	
	private global::Gtk.VBox vbox8;
	
	private global::Gtk.HBox hbox6;
	
	private global::Gtk.HBox hbox8;
	
	private global::Gtk.HBox hbox13;
	
	private global::Gtk.VBox vbox9;
	
	private global::Gtk.Label label7;
	
	private global::Gtk.Entry txtRubrik;
	
	private global::Gtk.VBox vbox10;
	
	private global::Gtk.Label label8;
	
	private global::Gtk.Entry txtStadt;
	
	private global::Gtk.HBox hbox7;
	
	private global::Gtk.VBox vbox11;
	
	private global::Gtk.Label label9;
	
	private global::Gtk.Entry txtMinGrosse;
	
	private global::Gtk.VBox vbox12;
	
	private global::Gtk.Label label10;
	
	private global::Gtk.Entry txtMaxMiete;
	
	private global::Gtk.HBox hbox9;
	
	private global::Gtk.HBox hbox10;
	
	private global::Gtk.HBox hbox11;
	
	private global::Gtk.HBox hbox12;
	
	private global::Gtk.VBox vbox13;
	
	private global::Gtk.Label label11;
	
	private global::Gtk.Entry txtMietart;
	
	private global::Gtk.Fixed fixed2;
	
	private global::Gtk.Fixed fixed3;
	
	private global::Gtk.VBox vbox14;
	
	private global::Gtk.VBox vbox3;
	
	private global::Gtk.HSeparator hseparator2;
	
	private global::Gtk.Label lblEinzugsdatum;
	
	private global::Gtk.HBox hbox14;
	
	private global::Gtk.HBox hbox15;
	
	private global::Gtk.VBox vbox15;
	
	private global::Gtk.Label label13;
	
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.HBox hbox1;
	
	private global::Gtk.Entry txtFruhestens;
	
	private global::Gtk.ToggleButton toggleCalendarFrom;
	
	private global::Gtk.Calendar calFrom;
	
	private global::Gtk.VBox vbox16;
	
	private global::Gtk.VBox vbox26;
	
	private global::Gtk.Label lblSpatestens;
	
	private global::Gtk.HBox hbox2;
	
	private global::Gtk.Entry txtSpatestens;
	
	private global::Gtk.ToggleButton toggleCalendarTo;
	
	private global::Gtk.Calendar calTo;
	
	private global::Gtk.HBox hbox16;
	
	private global::Gtk.Fixed fixed4;
	
	private global::Gtk.Fixed fixed5;
	
	private global::Gtk.VBox vbox17;
	
	private global::Gtk.VBox vbox24;
	
	private global::Gtk.HSeparator hseparator3;
	
	private global::Gtk.Label lblWgDetails;
	
	private global::Gtk.HBox hbox17;
	
	private global::Gtk.HBox hbox18;
	
	private global::Gtk.VBox vbox18;
	
	private global::Gtk.Label label16;
	
	private global::Gtk.ComboBox combobox1;
	
	private global::Gtk.Fixed fixed6;
	
	private global::Gtk.HBox hbox19;
	
	private global::Gtk.VBox vbox19;
	
	private global::Gtk.Label label17;
	
	private global::Gtk.ComboBox combobox2;
	
	private global::Gtk.VBox vbox20;
	
	private global::Gtk.Label label18;
	
	private global::Gtk.ComboBox combobox3;
	
	private global::Gtk.HBox hbox20;
	
	private global::Gtk.HBox hbox22;
	
	private global::Gtk.VBox vbox21;
	
	private global::Gtk.Label label19;
	
	private global::Gtk.ComboBox combobox4;
	
	private global::Gtk.VBox vbox22;
	
	private global::Gtk.Alignment alignment2;
	
	private global::Gtk.Fixed fixed7;
	
	private global::Gtk.HBox hbox23;
	
	private global::Gtk.CheckButton checkbutton1;
	
	private global::Gtk.HBox hbox21;
	
	private global::Gtk.VBox vbox23;
	
	private global::Gtk.Fixed fixed8;
	
	private global::Gtk.CheckButton checkbutton2;
	
	private global::Gtk.VBox vbox25;
	
	private global::Gtk.Fixed fixed9;
	
	private global::Gtk.CheckButton checkbutton3;
	
	private global::Gtk.HBox hbox5;
	
	private global::Gtk.Button btnBack2;
	
	private global::Gtk.Alignment alignment1;
	
	private global::Gtk.Fixed fixed1;
	
	private global::Gtk.Button btnForward2;
	
	private global::Gtk.Label pgSchritt2;
	
	private global::Gtk.Label pgSchritt3;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("WGDetektiv");
		this.Icon = global::Gdk.Pixbuf.LoadFromResource ("TestGtkGui.bin.Debug.images.search_button_green.png");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.Resizable = false;
		this.AllowGrow = false;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		// Container child hbox3.Gtk.Box+BoxChild
		this.imgLogo = new global::Gtk.Image ();
		this.imgLogo.Name = "imgLogo";
		this.imgLogo.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("TestGtkGui.bin.Debug.images.wg_detektiv_logo.png");
		this.hbox3.Add (this.imgLogo);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.imgLogo]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		// Container child hbox4.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		// Container child vbox2.Gtk.Box+BoxChild
		this.fixed10 = new global::Gtk.Fixed ();
		this.fixed10.HeightRequest = 37;
		this.fixed10.Name = "fixed10";
		this.fixed10.HasWindow = false;
		this.vbox2.Add (this.fixed10);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.fixed10]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox24 = new global::Gtk.HBox ();
		this.hbox24.Name = "hbox24";
		// Container child hbox24.Gtk.Box+BoxChild
		this.hbox25 = new global::Gtk.HBox ();
		this.hbox25.Name = "hbox25";
		this.hbox24.Add (this.hbox25);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox24 [this.hbox25]));
		w3.Position = 0;
		// Container child hbox24.Gtk.Box+BoxChild
		this.hbox26 = new global::Gtk.HBox ();
		this.hbox26.Name = "hbox26";
		this.hbox24.Add (this.hbox26);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox24 [this.hbox26]));
		w4.Position = 1;
		this.vbox2.Add (this.hbox24);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox24]));
		w5.Position = 1;
		this.hbox4.Add (this.vbox2);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.vbox2]));
		w6.Position = 0;
		this.hbox3.Add (this.hbox4);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.hbox4]));
		w7.Position = 1;
		this.vbox4.Add (this.hbox3);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox3]));
		w8.Position = 0;
		w8.Expand = false;
		w8.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.vbox5 = new global::Gtk.VBox ();
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 6;
		// Container child vbox5.Gtk.Box+BoxChild
		this.notebook2 = new global::Gtk.Notebook ();
		this.notebook2.CanFocus = true;
		this.notebook2.Name = "notebook2";
		this.notebook2.CurrentPage = 1;
		this.notebook2.ShowTabs = false;
		this.notebook2.BorderWidth = ((uint)(1));
		// Notebook tab
		global::Gtk.Label w9 = new global::Gtk.Label ();
		w9.Visible = true;
		this.notebook2.Add (w9);
		this.pgShritt1 = new global::Gtk.Label ();
		this.pgShritt1.Name = "pgShritt1";
		this.pgShritt1.LabelProp = global::Mono.Unix.Catalog.GetString ("Schritt 1");
		this.notebook2.SetTabLabel (w9, this.pgShritt1);
		this.pgShritt1.ShowAll ();
		// Container child notebook2.Gtk.Notebook+NotebookChild
		this.vbox6 = new global::Gtk.VBox ();
		this.vbox6.Name = "vbox6";
		this.vbox6.Spacing = 6;
		this.vbox6.BorderWidth = ((uint)(9));
		// Container child vbox6.Gtk.Box+BoxChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Hier kannst du die Suchkriterien für die WGs festlegen. Leere Felder werden als \"" +
		"egal\" gewertet.");
		this.vbox6.Add (this.label5);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.label5]));
		w10.Position = 0;
		w10.Expand = false;
		w10.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.vbox7 = new global::Gtk.VBox ();
		this.vbox7.Name = "vbox7";
		this.vbox7.Spacing = 6;
		// Container child vbox7.Gtk.Box+BoxChild
		this.vbox8 = new global::Gtk.VBox ();
		this.vbox8.Name = "vbox8";
		this.vbox8.Spacing = 6;
		this.vbox8.BorderWidth = ((uint)(6));
		// Container child vbox8.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox ();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.hbox8 = new global::Gtk.HBox ();
		this.hbox8.Name = "hbox8";
		this.hbox8.Spacing = 6;
		// Container child hbox8.Gtk.Box+BoxChild
		this.hbox13 = new global::Gtk.HBox ();
		this.hbox13.Name = "hbox13";
		this.hbox13.Spacing = 6;
		// Container child hbox13.Gtk.Box+BoxChild
		this.vbox9 = new global::Gtk.VBox ();
		this.vbox9.Name = "vbox9";
		this.vbox9.Spacing = 6;
		// Container child vbox9.Gtk.Box+BoxChild
		this.label7 = new global::Gtk.Label ();
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Rubrik:");
		this.vbox9.Add (this.label7);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.label7]));
		w11.Position = 0;
		w11.Expand = false;
		w11.Fill = false;
		// Container child vbox9.Gtk.Box+BoxChild
		this.txtRubrik = new global::Gtk.Entry ();
		this.txtRubrik.CanFocus = true;
		this.txtRubrik.Name = "txtRubrik";
		this.txtRubrik.IsEditable = true;
		this.txtRubrik.InvisibleChar = '●';
		this.vbox9.Add (this.txtRubrik);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.txtRubrik]));
		w12.Position = 1;
		w12.Expand = false;
		w12.Fill = false;
		w12.Padding = ((uint)(1));
		this.hbox13.Add (this.vbox9);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.vbox9]));
		w13.Position = 0;
		w13.Expand = false;
		w13.Fill = false;
		// Container child hbox13.Gtk.Box+BoxChild
		this.vbox10 = new global::Gtk.VBox ();
		this.vbox10.Name = "vbox10";
		this.vbox10.Spacing = 6;
		// Container child vbox10.Gtk.Box+BoxChild
		this.label8 = new global::Gtk.Label ();
		this.label8.Name = "label8";
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Stadt:");
		this.vbox10.Add (this.label8);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.label8]));
		w14.Position = 0;
		w14.Expand = false;
		w14.Fill = false;
		// Container child vbox10.Gtk.Box+BoxChild
		this.txtStadt = new global::Gtk.Entry ();
		this.txtStadt.CanFocus = true;
		this.txtStadt.Name = "txtStadt";
		this.txtStadt.IsEditable = true;
		this.txtStadt.InvisibleChar = '●';
		this.vbox10.Add (this.txtStadt);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.txtStadt]));
		w15.Position = 1;
		w15.Expand = false;
		w15.Fill = false;
		this.hbox13.Add (this.vbox10);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.vbox10]));
		w16.Position = 1;
		w16.Expand = false;
		w16.Fill = false;
		this.hbox8.Add (this.hbox13);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.hbox13]));
		w17.Position = 0;
		w17.Expand = false;
		w17.Fill = false;
		this.hbox6.Add (this.hbox8);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.hbox8]));
		w18.Position = 0;
		w18.Expand = false;
		w18.Fill = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.hbox7 = new global::Gtk.HBox ();
		this.hbox7.Name = "hbox7";
		this.hbox7.Spacing = 6;
		// Container child hbox7.Gtk.Box+BoxChild
		this.vbox11 = new global::Gtk.VBox ();
		this.vbox11.Name = "vbox11";
		this.vbox11.Spacing = 6;
		// Container child vbox11.Gtk.Box+BoxChild
		this.label9 = new global::Gtk.Label ();
		this.label9.Name = "label9";
		this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("min. Größe:");
		this.vbox11.Add (this.label9);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.label9]));
		w19.Position = 0;
		w19.Expand = false;
		w19.Fill = false;
		// Container child vbox11.Gtk.Box+BoxChild
		this.txtMinGrosse = new global::Gtk.Entry ();
		this.txtMinGrosse.CanFocus = true;
		this.txtMinGrosse.Name = "txtMinGrosse";
		this.txtMinGrosse.Text = global::Mono.Unix.Catalog.GetString ("m2");
		this.txtMinGrosse.IsEditable = true;
		this.txtMinGrosse.InvisibleChar = '●';
		this.txtMinGrosse.Xalign = 1F;
		this.vbox11.Add (this.txtMinGrosse);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.txtMinGrosse]));
		w20.Position = 1;
		w20.Expand = false;
		w20.Fill = false;
		this.hbox7.Add (this.vbox11);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.vbox11]));
		w21.Position = 0;
		w21.Expand = false;
		w21.Fill = false;
		// Container child hbox7.Gtk.Box+BoxChild
		this.vbox12 = new global::Gtk.VBox ();
		this.vbox12.Name = "vbox12";
		this.vbox12.Spacing = 6;
		// Container child vbox12.Gtk.Box+BoxChild
		this.label10 = new global::Gtk.Label ();
		this.label10.Name = "label10";
		this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("max. Miete:");
		this.vbox12.Add (this.label10);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox12 [this.label10]));
		w22.Position = 0;
		w22.Expand = false;
		w22.Fill = false;
		// Container child vbox12.Gtk.Box+BoxChild
		this.txtMaxMiete = new global::Gtk.Entry ();
		this.txtMaxMiete.CanFocus = true;
		this.txtMaxMiete.Name = "txtMaxMiete";
		this.txtMaxMiete.Text = global::Mono.Unix.Catalog.GetString ("€");
		this.txtMaxMiete.IsEditable = true;
		this.txtMaxMiete.InvisibleChar = '●';
		this.txtMaxMiete.Xalign = 1F;
		this.vbox12.Add (this.txtMaxMiete);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox12 [this.txtMaxMiete]));
		w23.Position = 1;
		w23.Expand = false;
		w23.Fill = false;
		this.hbox7.Add (this.vbox12);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.vbox12]));
		w24.Position = 1;
		w24.Expand = false;
		w24.Fill = false;
		this.hbox6.Add (this.hbox7);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.hbox7]));
		w25.Position = 1;
		w25.Expand = false;
		w25.Fill = false;
		this.vbox8.Add (this.hbox6);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.hbox6]));
		w26.Position = 0;
		w26.Expand = false;
		w26.Fill = false;
		// Container child vbox8.Gtk.Box+BoxChild
		this.hbox9 = new global::Gtk.HBox ();
		this.hbox9.Name = "hbox9";
		this.hbox9.Spacing = 6;
		// Container child hbox9.Gtk.Box+BoxChild
		this.hbox10 = new global::Gtk.HBox ();
		this.hbox10.Name = "hbox10";
		this.hbox10.Spacing = 6;
		// Container child hbox10.Gtk.Box+BoxChild
		this.hbox11 = new global::Gtk.HBox ();
		this.hbox11.Name = "hbox11";
		this.hbox11.Spacing = 6;
		// Container child hbox11.Gtk.Box+BoxChild
		this.hbox12 = new global::Gtk.HBox ();
		this.hbox12.Name = "hbox12";
		this.hbox12.Spacing = 6;
		// Container child hbox12.Gtk.Box+BoxChild
		this.vbox13 = new global::Gtk.VBox ();
		this.vbox13.Name = "vbox13";
		this.vbox13.Spacing = 6;
		// Container child vbox13.Gtk.Box+BoxChild
		this.label11 = new global::Gtk.Label ();
		this.label11.Name = "label11";
		this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("Mietart:");
		this.vbox13.Add (this.label11);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox13 [this.label11]));
		w27.Position = 0;
		w27.Expand = false;
		w27.Fill = false;
		// Container child vbox13.Gtk.Box+BoxChild
		this.txtMietart = new global::Gtk.Entry ();
		this.txtMietart.CanFocus = true;
		this.txtMietart.Name = "txtMietart";
		this.txtMietart.IsEditable = true;
		this.txtMietart.InvisibleChar = '●';
		this.vbox13.Add (this.txtMietart);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox13 [this.txtMietart]));
		w28.Position = 1;
		w28.Expand = false;
		w28.Fill = false;
		this.hbox12.Add (this.vbox13);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.vbox13]));
		w29.Position = 0;
		w29.Expand = false;
		w29.Fill = false;
		// Container child hbox12.Gtk.Box+BoxChild
		this.fixed2 = new global::Gtk.Fixed ();
		this.fixed2.Name = "fixed2";
		this.fixed2.HasWindow = false;
		this.hbox12.Add (this.fixed2);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.fixed2]));
		w30.Position = 1;
		this.hbox11.Add (this.hbox12);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.hbox12]));
		w31.Position = 0;
		this.hbox10.Add (this.hbox11);
		global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.hbox11]));
		w32.Position = 0;
		this.hbox9.Add (this.hbox10);
		global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.hbox10]));
		w33.Position = 0;
		// Container child hbox9.Gtk.Box+BoxChild
		this.fixed3 = new global::Gtk.Fixed ();
		this.fixed3.Name = "fixed3";
		this.fixed3.HasWindow = false;
		this.hbox9.Add (this.fixed3);
		global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.fixed3]));
		w34.Position = 1;
		this.vbox8.Add (this.hbox9);
		global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.hbox9]));
		w35.Position = 1;
		w35.Expand = false;
		w35.Fill = false;
		this.vbox7.Add (this.vbox8);
		global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.vbox8]));
		w36.Position = 0;
		w36.Expand = false;
		w36.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.vbox14 = new global::Gtk.VBox ();
		this.vbox14.Name = "vbox14";
		this.vbox14.Spacing = 6;
		this.vbox14.BorderWidth = ((uint)(6));
		// Container child vbox14.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hseparator2 = new global::Gtk.HSeparator ();
		this.hseparator2.Name = "hseparator2";
		this.vbox3.Add (this.hseparator2);
		global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hseparator2]));
		w37.Position = 0;
		w37.Expand = false;
		w37.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.lblEinzugsdatum = new global::Gtk.Label ();
		this.lblEinzugsdatum.Name = "lblEinzugsdatum";
		this.lblEinzugsdatum.Xalign = 0F;
		this.lblEinzugsdatum.LabelProp = global::Mono.Unix.Catalog.GetString ("Einzugsdatum");
		this.lblEinzugsdatum.UseMarkup = true;
		this.lblEinzugsdatum.UseUnderline = true;
		this.vbox3.Add (this.lblEinzugsdatum);
		global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.lblEinzugsdatum]));
		w38.Position = 1;
		w38.Expand = false;
		w38.Fill = false;
		this.vbox14.Add (this.vbox3);
		global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.vbox14 [this.vbox3]));
		w39.Position = 0;
		w39.Expand = false;
		w39.Fill = false;
		// Container child vbox14.Gtk.Box+BoxChild
		this.hbox14 = new global::Gtk.HBox ();
		this.hbox14.Name = "hbox14";
		this.hbox14.Spacing = 6;
		// Container child hbox14.Gtk.Box+BoxChild
		this.hbox15 = new global::Gtk.HBox ();
		this.hbox15.Name = "hbox15";
		this.hbox15.Spacing = 6;
		// Container child hbox15.Gtk.Box+BoxChild
		this.vbox15 = new global::Gtk.VBox ();
		this.vbox15.Name = "vbox15";
		this.vbox15.Spacing = 6;
		// Container child vbox15.Gtk.Box+BoxChild
		this.label13 = new global::Gtk.Label ();
		this.label13.Name = "label13";
		this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("Frühestens:");
		this.vbox15.Add (this.label13);
		global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.vbox15 [this.label13]));
		w40.Position = 0;
		w40.Expand = false;
		w40.Fill = false;
		// Container child vbox15.Gtk.Box+BoxChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.txtFruhestens = new global::Gtk.Entry ();
		this.txtFruhestens.CanFocus = true;
		this.txtFruhestens.Name = "txtFruhestens";
		this.txtFruhestens.IsEditable = true;
		this.txtFruhestens.InvisibleChar = '●';
		this.hbox1.Add (this.txtFruhestens);
		global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.txtFruhestens]));
		w41.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.toggleCalendarFrom = new global::Gtk.ToggleButton ();
		this.toggleCalendarFrom.CanFocus = true;
		this.toggleCalendarFrom.Name = "toggleCalendarFrom";
		this.toggleCalendarFrom.UseUnderline = true;
		global::Gtk.Image w42 = new global::Gtk.Image ();
		w42.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("TestGtkGui.bin.Debug.images.text_calendar.png");
		this.toggleCalendarFrom.Image = w42;
		this.hbox1.Add (this.toggleCalendarFrom);
		global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.toggleCalendarFrom]));
		w43.Position = 1;
		w43.Expand = false;
		w43.Fill = false;
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
		w44.Position = 0;
		w44.Expand = false;
		w44.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.calFrom = new global::Gtk.Calendar ();
		this.calFrom.CanFocus = true;
		this.calFrom.Name = "calFrom";
		this.calFrom.DisplayOptions = ((global::Gtk.CalendarDisplayOptions)(35));
		this.vbox1.Add (this.calFrom);
		global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.calFrom]));
		w45.Position = 1;
		w45.Expand = false;
		w45.Fill = false;
		this.vbox15.Add (this.vbox1);
		global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.vbox15 [this.vbox1]));
		w46.Position = 1;
		w46.Expand = false;
		w46.Fill = false;
		this.hbox15.Add (this.vbox15);
		global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.hbox15 [this.vbox15]));
		w47.Position = 0;
		w47.Expand = false;
		w47.Fill = false;
		// Container child hbox15.Gtk.Box+BoxChild
		this.vbox16 = new global::Gtk.VBox ();
		this.vbox16.Name = "vbox16";
		this.vbox16.Spacing = 6;
		// Container child vbox16.Gtk.Box+BoxChild
		this.vbox26 = new global::Gtk.VBox ();
		this.vbox26.Name = "vbox26";
		this.vbox26.Spacing = 6;
		// Container child vbox26.Gtk.Box+BoxChild
		this.lblSpatestens = new global::Gtk.Label ();
		this.lblSpatestens.Name = "lblSpatestens";
		this.lblSpatestens.LabelProp = global::Mono.Unix.Catalog.GetString ("Spätestens:");
		this.vbox26.Add (this.lblSpatestens);
		global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.vbox26 [this.lblSpatestens]));
		w48.Position = 0;
		w48.Expand = false;
		w48.Fill = false;
		// Container child vbox26.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.txtSpatestens = new global::Gtk.Entry ();
		this.txtSpatestens.CanFocus = true;
		this.txtSpatestens.Name = "txtSpatestens";
		this.txtSpatestens.IsEditable = true;
		this.txtSpatestens.InvisibleChar = '●';
		this.hbox2.Add (this.txtSpatestens);
		global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.txtSpatestens]));
		w49.Position = 0;
		// Container child hbox2.Gtk.Box+BoxChild
		this.toggleCalendarTo = new global::Gtk.ToggleButton ();
		this.toggleCalendarTo.CanFocus = true;
		this.toggleCalendarTo.Name = "toggleCalendarTo";
		this.toggleCalendarTo.UseUnderline = true;
		global::Gtk.Image w50 = new global::Gtk.Image ();
		w50.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("TestGtkGui.bin.Debug.images.text_calendar.png");
		this.toggleCalendarTo.Image = w50;
		this.hbox2.Add (this.toggleCalendarTo);
		global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.toggleCalendarTo]));
		w51.Position = 1;
		w51.Expand = false;
		w51.Fill = false;
		this.vbox26.Add (this.hbox2);
		global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.vbox26 [this.hbox2]));
		w52.Position = 1;
		w52.Expand = false;
		w52.Fill = false;
		this.vbox16.Add (this.vbox26);
		global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.vbox16 [this.vbox26]));
		w53.Position = 0;
		w53.Expand = false;
		w53.Fill = false;
		// Container child vbox16.Gtk.Box+BoxChild
		this.calTo = new global::Gtk.Calendar ();
		this.calTo.CanFocus = true;
		this.calTo.Name = "calTo";
		this.calTo.DisplayOptions = ((global::Gtk.CalendarDisplayOptions)(35));
		this.vbox16.Add (this.calTo);
		global::Gtk.Box.BoxChild w54 = ((global::Gtk.Box.BoxChild)(this.vbox16 [this.calTo]));
		w54.Position = 1;
		w54.Expand = false;
		w54.Fill = false;
		this.hbox15.Add (this.vbox16);
		global::Gtk.Box.BoxChild w55 = ((global::Gtk.Box.BoxChild)(this.hbox15 [this.vbox16]));
		w55.Position = 1;
		w55.Expand = false;
		w55.Fill = false;
		this.hbox14.Add (this.hbox15);
		global::Gtk.Box.BoxChild w56 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.hbox15]));
		w56.Position = 0;
		w56.Expand = false;
		w56.Fill = false;
		// Container child hbox14.Gtk.Box+BoxChild
		this.hbox16 = new global::Gtk.HBox ();
		this.hbox16.Name = "hbox16";
		this.hbox16.Spacing = 6;
		// Container child hbox16.Gtk.Box+BoxChild
		this.fixed4 = new global::Gtk.Fixed ();
		this.fixed4.Name = "fixed4";
		this.fixed4.HasWindow = false;
		this.hbox16.Add (this.fixed4);
		global::Gtk.Box.BoxChild w57 = ((global::Gtk.Box.BoxChild)(this.hbox16 [this.fixed4]));
		w57.Position = 0;
		// Container child hbox16.Gtk.Box+BoxChild
		this.fixed5 = new global::Gtk.Fixed ();
		this.fixed5.Name = "fixed5";
		this.fixed5.HasWindow = false;
		this.hbox16.Add (this.fixed5);
		global::Gtk.Box.BoxChild w58 = ((global::Gtk.Box.BoxChild)(this.hbox16 [this.fixed5]));
		w58.Position = 1;
		this.hbox14.Add (this.hbox16);
		global::Gtk.Box.BoxChild w59 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.hbox16]));
		w59.Position = 1;
		this.vbox14.Add (this.hbox14);
		global::Gtk.Box.BoxChild w60 = ((global::Gtk.Box.BoxChild)(this.vbox14 [this.hbox14]));
		w60.Position = 1;
		w60.Expand = false;
		w60.Fill = false;
		this.vbox7.Add (this.vbox14);
		global::Gtk.Box.BoxChild w61 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.vbox14]));
		w61.Position = 1;
		w61.Expand = false;
		w61.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.vbox17 = new global::Gtk.VBox ();
		this.vbox17.Name = "vbox17";
		this.vbox17.Spacing = 6;
		this.vbox17.BorderWidth = ((uint)(6));
		// Container child vbox17.Gtk.Box+BoxChild
		this.vbox24 = new global::Gtk.VBox ();
		this.vbox24.Name = "vbox24";
		this.vbox24.Spacing = 6;
		// Container child vbox24.Gtk.Box+BoxChild
		this.hseparator3 = new global::Gtk.HSeparator ();
		this.hseparator3.Name = "hseparator3";
		this.vbox24.Add (this.hseparator3);
		global::Gtk.Box.BoxChild w62 = ((global::Gtk.Box.BoxChild)(this.vbox24 [this.hseparator3]));
		w62.Position = 0;
		w62.Expand = false;
		w62.Fill = false;
		// Container child vbox24.Gtk.Box+BoxChild
		this.lblWgDetails = new global::Gtk.Label ();
		this.lblWgDetails.Name = "lblWgDetails";
		this.lblWgDetails.Xalign = 0F;
		this.lblWgDetails.LabelProp = global::Mono.Unix.Catalog.GetString ("WG Details");
		this.vbox24.Add (this.lblWgDetails);
		global::Gtk.Box.BoxChild w63 = ((global::Gtk.Box.BoxChild)(this.vbox24 [this.lblWgDetails]));
		w63.Position = 1;
		w63.Expand = false;
		w63.Fill = false;
		this.vbox17.Add (this.vbox24);
		global::Gtk.Box.BoxChild w64 = ((global::Gtk.Box.BoxChild)(this.vbox17 [this.vbox24]));
		w64.Position = 0;
		w64.Expand = false;
		w64.Fill = false;
		// Container child vbox17.Gtk.Box+BoxChild
		this.hbox17 = new global::Gtk.HBox ();
		this.hbox17.Name = "hbox17";
		this.hbox17.Spacing = 6;
		// Container child hbox17.Gtk.Box+BoxChild
		this.hbox18 = new global::Gtk.HBox ();
		this.hbox18.Name = "hbox18";
		this.hbox18.Spacing = 6;
		// Container child hbox18.Gtk.Box+BoxChild
		this.vbox18 = new global::Gtk.VBox ();
		this.vbox18.Name = "vbox18";
		this.vbox18.Spacing = 6;
		// Container child vbox18.Gtk.Box+BoxChild
		this.label16 = new global::Gtk.Label ();
		this.label16.Name = "label16";
		this.label16.LabelProp = global::Mono.Unix.Catalog.GetString ("Geschlecht mitbewoher:");
		this.vbox18.Add (this.label16);
		global::Gtk.Box.BoxChild w65 = ((global::Gtk.Box.BoxChild)(this.vbox18 [this.label16]));
		w65.Position = 0;
		w65.Expand = false;
		w65.Fill = false;
		// Container child vbox18.Gtk.Box+BoxChild
		this.combobox1 = global::Gtk.ComboBox.NewText ();
		this.combobox1.AppendText (global::Mono.Unix.Catalog.GetString ("Geschlecht egal"));
		this.combobox1.AppendText (global::Mono.Unix.Catalog.GetString ("nur Frauen"));
		this.combobox1.AppendText (global::Mono.Unix.Catalog.GetString ("nur Männer"));
		this.combobox1.AppendText (global::Mono.Unix.Catalog.GetString ("nur gemischte WG"));
		this.combobox1.WidthRequest = 170;
		this.combobox1.Name = "combobox1";
		this.combobox1.Active = 0;
		this.vbox18.Add (this.combobox1);
		global::Gtk.Box.BoxChild w66 = ((global::Gtk.Box.BoxChild)(this.vbox18 [this.combobox1]));
		w66.Position = 1;
		w66.Expand = false;
		w66.Fill = false;
		this.hbox18.Add (this.vbox18);
		global::Gtk.Box.BoxChild w67 = ((global::Gtk.Box.BoxChild)(this.hbox18 [this.vbox18]));
		w67.Position = 0;
		w67.Expand = false;
		w67.Fill = false;
		// Container child hbox18.Gtk.Box+BoxChild
		this.fixed6 = new global::Gtk.Fixed ();
		this.fixed6.Name = "fixed6";
		this.fixed6.HasWindow = false;
		this.hbox18.Add (this.fixed6);
		global::Gtk.Box.BoxChild w68 = ((global::Gtk.Box.BoxChild)(this.hbox18 [this.fixed6]));
		w68.Position = 1;
		this.hbox17.Add (this.hbox18);
		global::Gtk.Box.BoxChild w69 = ((global::Gtk.Box.BoxChild)(this.hbox17 [this.hbox18]));
		w69.Position = 0;
		// Container child hbox17.Gtk.Box+BoxChild
		this.hbox19 = new global::Gtk.HBox ();
		this.hbox19.Name = "hbox19";
		this.hbox19.Spacing = 6;
		// Container child hbox19.Gtk.Box+BoxChild
		this.vbox19 = new global::Gtk.VBox ();
		this.vbox19.Name = "vbox19";
		this.vbox19.Spacing = 6;
		// Container child vbox19.Gtk.Box+BoxChild
		this.label17 = new global::Gtk.Label ();
		this.label17.Name = "label17";
		this.label17.LabelProp = global::Mono.Unix.Catalog.GetString ("Rauchen:");
		this.vbox19.Add (this.label17);
		global::Gtk.Box.BoxChild w70 = ((global::Gtk.Box.BoxChild)(this.vbox19 [this.label17]));
		w70.Position = 0;
		w70.Expand = false;
		w70.Fill = false;
		// Container child vbox19.Gtk.Box+BoxChild
		this.combobox2 = global::Gtk.ComboBox.NewText ();
		this.combobox2.AppendText (global::Mono.Unix.Catalog.GetString ("egal"));
		this.combobox2.AppendText (global::Mono.Unix.Catalog.GetString ("erlaubt"));
		this.combobox2.AppendText (global::Mono.Unix.Catalog.GetString ("nicht erwünscht"));
		this.combobox2.AppendText (global::Mono.Unix.Catalog.GetString ("im eigenen Zimmer"));
		this.combobox2.WidthRequest = 170;
		this.combobox2.Name = "combobox2";
		this.combobox2.Active = 0;
		this.vbox19.Add (this.combobox2);
		global::Gtk.Box.BoxChild w71 = ((global::Gtk.Box.BoxChild)(this.vbox19 [this.combobox2]));
		w71.Position = 1;
		w71.Expand = false;
		w71.Fill = false;
		this.hbox19.Add (this.vbox19);
		global::Gtk.Box.BoxChild w72 = ((global::Gtk.Box.BoxChild)(this.hbox19 [this.vbox19]));
		w72.Position = 0;
		w72.Expand = false;
		w72.Fill = false;
		// Container child hbox19.Gtk.Box+BoxChild
		this.vbox20 = new global::Gtk.VBox ();
		this.vbox20.Name = "vbox20";
		this.vbox20.Spacing = 6;
		// Container child vbox20.Gtk.Box+BoxChild
		this.label18 = new global::Gtk.Label ();
		this.label18.Name = "label18";
		this.label18.LabelProp = global::Mono.Unix.Catalog.GetString ("Anzahl Mitbewoher:");
		this.vbox20.Add (this.label18);
		global::Gtk.Box.BoxChild w73 = ((global::Gtk.Box.BoxChild)(this.vbox20 [this.label18]));
		w73.Position = 0;
		w73.Expand = false;
		w73.Fill = false;
		// Container child vbox20.Gtk.Box+BoxChild
		this.combobox3 = global::Gtk.ComboBox.NewText ();
		this.combobox3.AppendText (global::Mono.Unix.Catalog.GetString ("egal"));
		this.combobox3.AppendText (global::Mono.Unix.Catalog.GetString ("1"));
		this.combobox3.AppendText (global::Mono.Unix.Catalog.GetString ("2"));
		this.combobox3.AppendText (global::Mono.Unix.Catalog.GetString ("3"));
		this.combobox3.AppendText (global::Mono.Unix.Catalog.GetString ("4"));
		this.combobox3.AppendText (global::Mono.Unix.Catalog.GetString ("5"));
		this.combobox3.WidthRequest = 170;
		this.combobox3.Name = "combobox3";
		this.combobox3.Active = 0;
		this.vbox20.Add (this.combobox3);
		global::Gtk.Box.BoxChild w74 = ((global::Gtk.Box.BoxChild)(this.vbox20 [this.combobox3]));
		w74.Position = 1;
		w74.Expand = false;
		w74.Fill = false;
		this.hbox19.Add (this.vbox20);
		global::Gtk.Box.BoxChild w75 = ((global::Gtk.Box.BoxChild)(this.hbox19 [this.vbox20]));
		w75.Position = 1;
		w75.Expand = false;
		w75.Fill = false;
		this.hbox17.Add (this.hbox19);
		global::Gtk.Box.BoxChild w76 = ((global::Gtk.Box.BoxChild)(this.hbox17 [this.hbox19]));
		w76.Position = 1;
		w76.Expand = false;
		w76.Fill = false;
		this.vbox17.Add (this.hbox17);
		global::Gtk.Box.BoxChild w77 = ((global::Gtk.Box.BoxChild)(this.vbox17 [this.hbox17]));
		w77.Position = 1;
		w77.Expand = false;
		w77.Fill = false;
		// Container child vbox17.Gtk.Box+BoxChild
		this.hbox20 = new global::Gtk.HBox ();
		this.hbox20.Name = "hbox20";
		this.hbox20.Spacing = 6;
		// Container child hbox20.Gtk.Box+BoxChild
		this.hbox22 = new global::Gtk.HBox ();
		this.hbox22.Name = "hbox22";
		this.hbox22.Spacing = 6;
		// Container child hbox22.Gtk.Box+BoxChild
		this.vbox21 = new global::Gtk.VBox ();
		this.vbox21.Name = "vbox21";
		this.vbox21.Spacing = 6;
		// Container child vbox21.Gtk.Box+BoxChild
		this.label19 = new global::Gtk.Label ();
		this.label19.WidthRequest = 140;
		this.label19.Name = "label19";
		this.label19.LabelProp = global::Mono.Unix.Catalog.GetString ("Haustiere:");
		this.vbox21.Add (this.label19);
		global::Gtk.Box.BoxChild w78 = ((global::Gtk.Box.BoxChild)(this.vbox21 [this.label19]));
		w78.Position = 0;
		w78.Expand = false;
		w78.Fill = false;
		// Container child vbox21.Gtk.Box+BoxChild
		this.combobox4 = global::Gtk.ComboBox.NewText ();
		this.combobox4.AppendText (global::Mono.Unix.Catalog.GetString ("egal"));
		this.combobox4.AppendText (global::Mono.Unix.Catalog.GetString ("Ja"));
		this.combobox4.AppendText (global::Mono.Unix.Catalog.GetString ("Nein"));
		this.combobox4.WidthRequest = 170;
		this.combobox4.Name = "combobox4";
		this.combobox4.Active = 0;
		this.vbox21.Add (this.combobox4);
		global::Gtk.Box.BoxChild w79 = ((global::Gtk.Box.BoxChild)(this.vbox21 [this.combobox4]));
		w79.Position = 1;
		w79.Expand = false;
		w79.Fill = false;
		this.hbox22.Add (this.vbox21);
		global::Gtk.Box.BoxChild w80 = ((global::Gtk.Box.BoxChild)(this.hbox22 [this.vbox21]));
		w80.Position = 0;
		w80.Expand = false;
		w80.Fill = false;
		// Container child hbox22.Gtk.Box+BoxChild
		this.vbox22 = new global::Gtk.VBox ();
		this.vbox22.Name = "vbox22";
		this.vbox22.Spacing = 6;
		// Container child vbox22.Gtk.Box+BoxChild
		this.alignment2 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.alignment2.Name = "alignment2";
		// Container child alignment2.Gtk.Container+ContainerChild
		this.fixed7 = new global::Gtk.Fixed ();
		this.fixed7.HeightRequest = 15;
		this.fixed7.Name = "fixed7";
		this.fixed7.HasWindow = false;
		this.alignment2.Add (this.fixed7);
		this.vbox22.Add (this.alignment2);
		global::Gtk.Box.BoxChild w82 = ((global::Gtk.Box.BoxChild)(this.vbox22 [this.alignment2]));
		w82.Position = 0;
		w82.Expand = false;
		w82.Fill = false;
		// Container child vbox22.Gtk.Box+BoxChild
		this.hbox23 = new global::Gtk.HBox ();
		this.hbox23.Name = "hbox23";
		this.hbox23.Spacing = 6;
		// Container child hbox23.Gtk.Box+BoxChild
		this.checkbutton1 = new global::Gtk.CheckButton ();
		this.checkbutton1.CanFocus = true;
		this.checkbutton1.Name = "checkbutton1";
		this.checkbutton1.Label = global::Mono.Unix.Catalog.GetString ("Balkon");
		this.checkbutton1.DrawIndicator = true;
		this.checkbutton1.UseUnderline = true;
		this.hbox23.Add (this.checkbutton1);
		global::Gtk.Box.BoxChild w83 = ((global::Gtk.Box.BoxChild)(this.hbox23 [this.checkbutton1]));
		w83.Position = 0;
		this.vbox22.Add (this.hbox23);
		global::Gtk.Box.BoxChild w84 = ((global::Gtk.Box.BoxChild)(this.vbox22 [this.hbox23]));
		w84.Position = 1;
		w84.Expand = false;
		w84.Fill = false;
		this.hbox22.Add (this.vbox22);
		global::Gtk.Box.BoxChild w85 = ((global::Gtk.Box.BoxChild)(this.hbox22 [this.vbox22]));
		w85.Position = 1;
		this.hbox20.Add (this.hbox22);
		global::Gtk.Box.BoxChild w86 = ((global::Gtk.Box.BoxChild)(this.hbox20 [this.hbox22]));
		w86.Position = 0;
		// Container child hbox20.Gtk.Box+BoxChild
		this.hbox21 = new global::Gtk.HBox ();
		this.hbox21.Name = "hbox21";
		this.hbox21.Spacing = 6;
		// Container child hbox21.Gtk.Box+BoxChild
		this.vbox23 = new global::Gtk.VBox ();
		this.vbox23.Name = "vbox23";
		this.vbox23.Spacing = 6;
		// Container child vbox23.Gtk.Box+BoxChild
		this.fixed8 = new global::Gtk.Fixed ();
		this.fixed8.HeightRequest = 15;
		this.fixed8.Name = "fixed8";
		this.fixed8.HasWindow = false;
		this.vbox23.Add (this.fixed8);
		global::Gtk.Box.BoxChild w87 = ((global::Gtk.Box.BoxChild)(this.vbox23 [this.fixed8]));
		w87.Position = 0;
		w87.Expand = false;
		w87.Fill = false;
		// Container child vbox23.Gtk.Box+BoxChild
		this.checkbutton2 = new global::Gtk.CheckButton ();
		this.checkbutton2.WidthRequest = 100;
		this.checkbutton2.CanFocus = true;
		this.checkbutton2.Name = "checkbutton2";
		this.checkbutton2.Label = global::Mono.Unix.Catalog.GetString ("Garten");
		this.checkbutton2.DrawIndicator = true;
		this.checkbutton2.UseUnderline = true;
		this.vbox23.Add (this.checkbutton2);
		global::Gtk.Box.BoxChild w88 = ((global::Gtk.Box.BoxChild)(this.vbox23 [this.checkbutton2]));
		w88.Position = 1;
		w88.Expand = false;
		w88.Fill = false;
		this.hbox21.Add (this.vbox23);
		global::Gtk.Box.BoxChild w89 = ((global::Gtk.Box.BoxChild)(this.hbox21 [this.vbox23]));
		w89.Position = 0;
		// Container child hbox21.Gtk.Box+BoxChild
		this.vbox25 = new global::Gtk.VBox ();
		this.vbox25.Name = "vbox25";
		this.vbox25.Spacing = 6;
		// Container child vbox25.Gtk.Box+BoxChild
		this.fixed9 = new global::Gtk.Fixed ();
		this.fixed9.HeightRequest = 15;
		this.fixed9.Name = "fixed9";
		this.fixed9.HasWindow = false;
		this.vbox25.Add (this.fixed9);
		global::Gtk.Box.BoxChild w90 = ((global::Gtk.Box.BoxChild)(this.vbox25 [this.fixed9]));
		w90.Position = 0;
		w90.Expand = false;
		w90.Fill = false;
		// Container child vbox25.Gtk.Box+BoxChild
		this.checkbutton3 = new global::Gtk.CheckButton ();
		this.checkbutton3.WidthRequest = 115;
		this.checkbutton3.CanFocus = true;
		this.checkbutton3.Name = "checkbutton3";
		this.checkbutton3.Label = global::Mono.Unix.Catalog.GetString ("Barrierefrei");
		this.checkbutton3.DrawIndicator = true;
		this.checkbutton3.UseUnderline = true;
		this.vbox25.Add (this.checkbutton3);
		global::Gtk.Box.BoxChild w91 = ((global::Gtk.Box.BoxChild)(this.vbox25 [this.checkbutton3]));
		w91.Position = 1;
		w91.Expand = false;
		w91.Fill = false;
		this.hbox21.Add (this.vbox25);
		global::Gtk.Box.BoxChild w92 = ((global::Gtk.Box.BoxChild)(this.hbox21 [this.vbox25]));
		w92.Position = 1;
		this.hbox20.Add (this.hbox21);
		global::Gtk.Box.BoxChild w93 = ((global::Gtk.Box.BoxChild)(this.hbox20 [this.hbox21]));
		w93.Position = 1;
		this.vbox17.Add (this.hbox20);
		global::Gtk.Box.BoxChild w94 = ((global::Gtk.Box.BoxChild)(this.vbox17 [this.hbox20]));
		w94.Position = 2;
		w94.Expand = false;
		w94.Fill = false;
		this.vbox7.Add (this.vbox17);
		global::Gtk.Box.BoxChild w95 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.vbox17]));
		w95.Position = 2;
		w95.Expand = false;
		w95.Fill = false;
		this.vbox6.Add (this.vbox7);
		global::Gtk.Box.BoxChild w96 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.vbox7]));
		w96.Position = 1;
		w96.Expand = false;
		w96.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox ();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		this.hbox5.BorderWidth = ((uint)(6));
		// Container child hbox5.Gtk.Box+BoxChild
		this.btnBack2 = new global::Gtk.Button ();
		this.btnBack2.CanFocus = true;
		this.btnBack2.Name = "btnBack2";
		this.btnBack2.UseUnderline = true;
		global::Gtk.Image w97 = new global::Gtk.Image ();
		w97.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("TestGtkGui.bin.Debug.images.arrow_left_green.png");
		this.btnBack2.Image = w97;
		this.hbox5.Add (this.btnBack2);
		global::Gtk.Box.BoxChild w98 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.btnBack2]));
		w98.Position = 0;
		w98.Expand = false;
		w98.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.alignment1 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.alignment1.Name = "alignment1";
		// Container child alignment1.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		this.alignment1.Add (this.fixed1);
		this.hbox5.Add (this.alignment1);
		global::Gtk.Box.BoxChild w100 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.alignment1]));
		w100.Position = 1;
		// Container child hbox5.Gtk.Box+BoxChild
		this.btnForward2 = new global::Gtk.Button ();
		this.btnForward2.CanFocus = true;
		this.btnForward2.Name = "btnForward2";
		this.btnForward2.UseUnderline = true;
		global::Gtk.Image w101 = new global::Gtk.Image ();
		w101.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("TestGtkGui.bin.Debug.images.arrow_right_green.png");
		this.btnForward2.Image = w101;
		this.hbox5.Add (this.btnForward2);
		global::Gtk.Box.BoxChild w102 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.btnForward2]));
		w102.Position = 2;
		w102.Expand = false;
		w102.Fill = false;
		this.vbox6.Add (this.hbox5);
		global::Gtk.Box.BoxChild w103 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox5]));
		w103.Position = 2;
		w103.Expand = false;
		w103.Fill = false;
		this.notebook2.Add (this.vbox6);
		global::Gtk.Notebook.NotebookChild w104 = ((global::Gtk.Notebook.NotebookChild)(this.notebook2 [this.vbox6]));
		w104.Position = 1;
		// Notebook tab
		this.pgSchritt2 = new global::Gtk.Label ();
		this.pgSchritt2.Name = "pgSchritt2";
		this.pgSchritt2.LabelProp = global::Mono.Unix.Catalog.GetString ("Schritt 2");
		this.notebook2.SetTabLabel (this.vbox6, this.pgSchritt2);
		this.pgSchritt2.ShowAll ();
		// Notebook tab
		global::Gtk.Label w105 = new global::Gtk.Label ();
		w105.Visible = true;
		this.notebook2.Add (w105);
		this.pgSchritt3 = new global::Gtk.Label ();
		this.pgSchritt3.Name = "pgSchritt3";
		this.pgSchritt3.LabelProp = global::Mono.Unix.Catalog.GetString ("Schritt 3");
		this.notebook2.SetTabLabel (w105, this.pgSchritt3);
		this.pgSchritt3.ShowAll ();
		this.vbox5.Add (this.notebook2);
		global::Gtk.Box.BoxChild w106 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.notebook2]));
		w106.Position = 0;
		this.vbox4.Add (this.vbox5);
		global::Gtk.Box.BoxChild w107 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.vbox5]));
		w107.Position = 1;
		this.Add (this.vbox4);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 822;
		this.DefaultHeight = 744;
		this.calFrom.Hide ();
		this.calTo.Hide ();
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.txtMinGrosse.FocusGrabbed += new global::System.EventHandler (this.OnTxtMinGrosseFocusGrabbed);
		this.txtMinGrosse.FocusOutEvent += new global::Gtk.FocusOutEventHandler (this.OnTxtMinGrosseFocusOutEvent);
		this.txtMaxMiete.FocusGrabbed += new global::System.EventHandler (this.OnTxtMaxMieteFocusGrabbed);
		this.txtMaxMiete.FocusOutEvent += new global::Gtk.FocusOutEventHandler (this.OnTxtMaxMieteFocusOutEvent);
		this.toggleCalendarFrom.Toggled += new global::System.EventHandler (this.OnToggleCalendarFromToggled);
		this.calFrom.DaySelected += new global::System.EventHandler (this.OnCalFromDaySelected);
		this.calFrom.DaySelectedDoubleClick += new global::System.EventHandler (this.OnCalFromDaySelectedDoubleClick);
		this.toggleCalendarTo.Toggled += new global::System.EventHandler (this.OnToggleCalendarToToggled);
		this.calTo.DaySelected += new global::System.EventHandler (this.OnCalToDaySelected);
		this.calTo.DaySelectedDoubleClick += new global::System.EventHandler (this.OnCalToDaySelectedDoubleClick);
	}
}
